### ISSUE TITLE
Login Error 500 status code  

### ISSUE THREAD

**Issue by SuhaibElramly** [Artisans-Digital-Agency/marwa-backend#10]
route `http://artisanstestsite.org.ly/api/v1/doctor/login`

Body: `{
    "username":"test_anas",
    "password":"123456789"
}`

![error_1](https://user-images.githubusercontent.com/68656359/97323135-2709df80-1879-11eb-8222-4a98f927252d.png)

![error_2](https://user-images.githubusercontent.com/68656359/97323162-2d985700-1879-11eb-950b-0b40006bb0b0.png)

**Comment by AmineKechroud** [comment]
very strangeit works locally, im on it
