### ISSUE TITLE
missing data in department detials

### ISSUE THREAD

**Issue by MnKashpour** [Artisans-Digital-Agency/marwa-backend#12]
Route: `/patient/departments/{department_id}`
Method: `GET`

there are some missing data which are needed
1) description header
2) Services

**Comment by AmineKechroud** [comment]
the services will be added today.
what do you mean by description header can you please elaborate with a picture?

**Comment by MnKashpour** [comment]
![IMG_20201028_155259.jpg](https://user-images.githubusercontent.com/54836508/97445226-b248ab00-1935-11eb-9124-e0a3d5ce1814.jpg)

**Comment by MnKashpour** [comment]
This is the description header
