### ISSUE TITLE
Departments #2

### ISSUE THREAD

**Issue by AnasShwehdy** [Artisans-Digital-Agency/marwa-backend#14]
### To the best of my knowledge, The departments section includes name, description, Devices(Images, description),  Services(Images, description)

Instead in the document, I found this table 

Type | Params | Example
-- | -- | --
String| name* | ""
String | description*|""
File |thumbnail*| file
_array_| _images_*|_[]_
_file_| _images_.*|_file_
_array_| _videos_*|_[]_
_file_  | _videos_.*|_file_

The italic records above require explanation <3

**Comment by AmineKechroud** [comment]
the services/devices are added separately (check docs).
the "images" and "videos" array are for the media content that could exist in a department (if we want a slider on top of department page)

**Comment by AnasShwehdy** [comment]
Cool
