### ISSUE TITLE
Improvment of documentation for departments

### ISSUE THREAD

**Issue by MnKashpour** [Artisans-Digital-Agency/marwa-backend#7]
What is description?

What is media?

will the details of the department have a different route?

**Comment by AmineKechroud** [comment]
yes the department details will have a different route.
media is the array the will hold the images/videos of the department.
description is the description of the app.

**Comment by MnKashpour** [comment]
@AmineKechroud 
if the department details will have a different route, then the description & media is not really needed in the `departments` route.
